name: default.aspx
favicon: null
layout_spectrum: 0.7391266564372927
typography_spectrum: 0.0538184461183846
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6178154009394348
  lightness: 0.31397495954297483
  saturation: 0.25185595359653234
  rhythmicContrast: 0.07523285411298275
purpose: []
